import { Link, useNavigate } from 'react-router-dom';
import { Building2, Factory, Home, LayoutTemplate, ArrowRight, Copy, CheckCircle2 } from 'lucide-react';

type Template={id:string;title:string;category:string;description:string;circuits:string;icon:typeof Home;data:Record<string,unknown>};

const templates:Template[]=[
 {id:'residencial-2-quartos',title:'Residência 2 Quartos',category:'Residencial',description:'Base para casa de 2 quartos, sistema bifásico 127/220 V e estrutura pronta para personalização.',circuits:'9 circuitos',icon:Home,data:{propertyType:'Residencial',purpose:'Residência unifamiliar',voltage:'127/220 V',phases:'Bifásico',rooms:[{name:'Sala',area:18,length:6,width:3},{name:'Quarto 1',area:12,length:4,width:3},{name:'Quarto 2',area:12,length:4,width:3},{name:'Cozinha',area:10,length:4,width:2.5},{name:'Banheiro',area:5,length:2.5,width:2},{name:'Área de serviço',area:6,length:3,width:2}],points:[]}},
 {id:'apartamento-compacto',title:'Apartamento Compacto',category:'Residencial',description:'Modelo enxuto para apartamento de pequeno porte, pronto para ajustar ambientes e cargas.',circuits:'6 circuitos',icon:Building2,data:{propertyType:'Residencial',purpose:'Apartamento',voltage:'127/220 V',phases:'Bifásico',rooms:[{name:'Sala',area:14,length:4.5,width:3},{name:'Quarto',area:10,length:3.5,width:3},{name:'Cozinha',area:8,length:3.2,width:2.5},{name:'Banheiro',area:4,length:2,width:2}],points:[]}},
 {id:'comercial-loja',title:'Loja / Pequeno Comércio',category:'Comercial',description:'Modelo para loja ou escritório, com ambientes e cargas que podem ser totalmente editados.',circuits:'8 circuitos',icon:Building2,data:{propertyType:'Comercial',purpose:'Loja / escritório',voltage:'127/220 V',phases:'Bifásico',rooms:[{name:'Atendimento',area:25,length:6.25,width:4},{name:'Escritório',area:12,length:4,width:3},{name:'Copa',area:7,length:3.5,width:2}],points:[]}},
 {id:'galpao-industrial',title:'Galpão Industrial',category:'Industrial',description:'Estrutura inicial para galpão, permitindo adaptar dimensões, máquinas e cargas específicas.',circuits:'Modelo base',icon:Factory,data:{propertyType:'Industrial',purpose:'Galpão / instalação industrial',voltage:'380/220 V',phases:'Trifásico',rooms:[{name:'Área de produção',area:120,length:15,width:8},{name:'Escritório',area:20,length:5,width:4},{name:'Depósito',area:30,length:6,width:5}],points:[]}},
];

export default function ProjectTemplatesPage(){
 const navigate=useNavigate();
 const useTemplate=(template:Template)=>{sessionStorage.setItem('electrocad_project_template',JSON.stringify(template.data));navigate('/projects');};
 return <div className="space-y-6 pb-12">
  <div><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-blue-600"><LayoutTemplate size={24}/></div><div><h2 className="text-3xl font-black text-slate-900">Modelos de Projetos</h2><p className="mt-1 text-sm text-slate-500">Comece com uma estrutura pronta e altere tudo conforme o projeto real do seu cliente.</p></div></div></div>
  <div className="rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900"><b>Como funciona:</b> escolha um modelo, informe o cliente e personalize ambientes, pontos, cargas, critérios e proteções. O modelo não altera nenhum projeto já salvo.</div>
  <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{templates.map(t=>{const Icon=t.icon;return <article key={t.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="bg-[#061a33] p-6 text-white"><Icon size={34} className="text-blue-400"/><h3 className="mt-5 text-xl font-black">{t.title}</h3><span className="mt-2 inline-block rounded-full bg-white/10 px-3 py-1 text-xs">{t.category} · {t.circuits}</span></div><div className="p-5"><p className="min-h-20 text-sm leading-6 text-slate-500">{t.description}</p><ul className="mt-4 space-y-2 text-xs text-slate-600"><li><CheckCircle2 className="mr-2 inline text-emerald-500" size={15}/>Estrutura inicial de ambientes</li><li><CheckCircle2 className="mr-2 inline text-emerald-500" size={15}/>Dados editáveis</li><li><CheckCircle2 className="mr-2 inline text-emerald-500" size={15}/>Novo projeto independente</li></ul><button onClick={()=>useTemplate(t)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white hover:bg-blue-500"><Copy size={16}/> Usar este modelo <ArrowRight size={16}/></button></div></article>})}</div>
  <section className="rounded-3xl border bg-white p-6"><h3 className="text-lg font-bold">Projetos já salvos</h3><p className="mt-1 text-sm text-slate-500">Para abrir, editar ou continuar um projeto criado anteriormente, use a área Projetos.</p><Link to="/projects" className="mt-4 inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold">Ir para Projetos <ArrowRight size={16}/></Link></section>
 </div>;
}
