import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { ArrowRight, Bot, Building2, CheckCircle2, FileText, Factory, Home, PlayCircle, ShieldCheck, Sparkles, Zap, Users, Calculator, FileCheck2 } from "lucide-react";
import { apiFetch } from "../services/api";

type Plan={id:string;name:string;price:string;trialDays:number;description:string;features:string[]};
const fallbackPlans:Plan[]=[
{id:"starter",name:"Starter",price:"R$ 49",trialDays:14,description:"Para quem está começando e quer organizar seus projetos.",features:["Projetos","Clientes","Planta 2D","IA básica"]},
{id:"pro",name:"Pro",price:"R$ 129",trialDays:30,description:"Produtividade para profissionais que trabalham com projetos.",features:["Tudo do Starter","Projetista elétrico","Professor IA","Relatórios avançados"]},
{id:"enterprise",name:"Enterprise",price:"R$ 299",trialDays:45,description:"Recursos completos para profissionais e empresas.",features:["Tudo do Pro","Maior capacidade","Recursos premium","Suporte diferenciado"]}];
const features=[{icon:ShieldCheck,title:"Conforme NBR 5410"},{icon:Zap,title:"Cálculos automáticos"},{icon:FileCheck2,title:"Diagramas unifilares"},{icon:FileText,title:"Lista de materiais"},{icon:FileText,title:"Relatórios profissionais"}];

export default function LandingPage(){
 const [plans,setPlans]=useState<Plan[]>(fallbackPlans);
 useEffect(()=>{let active=true;apiFetch("/plans",{cache:"no-store"}).then(d=>{if(active&&Array.isArray(d)&&d.length)setPlans(d)}).catch(()=>undefined);return()=>{active=false}},[]);
 return <div className="min-h-screen overflow-x-hidden bg-white text-slate-900">
  <header className="absolute inset-x-0 top-0 z-40 border-b border-white/10 bg-[#061426]/45 text-white backdrop-blur-md">
   <div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-4 lg:px-10">
    <Link to="/" className="flex items-center gap-3"><span className="text-4xl text-blue-400">⚡</span><div><div className="text-2xl font-black">ElectroCAD-AI</div><div className="text-[11px] text-slate-300">Dimensionamento Elétrico Inteligente</div></div></Link>
    <nav className="hidden items-center gap-7 text-sm font-medium lg:flex"><a href="#recursos">Recursos</a><a href="#planos">Planos</a><a href="#integracoes">Integrações</a><a href="#sobre">Sobre</a><a href="#contato">Contato</a></nav>
    <div className="flex gap-2"><Link to="/login" className="rounded-lg border border-white/50 px-5 py-2.5 text-sm font-semibold hover:bg-white/10">Entrar</Link><Link to="/register" className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold">Criar conta</Link></div>
   </div>
  </header>
  <main>
   <section className="relative min-h-[720px] overflow-hidden bg-[#061426] pt-28 text-white">
    <img src="/assets/electrocad-landing-hero.svg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-90"/><div className="absolute inset-0 bg-gradient-to-r from-[#061426] via-[#061426]/90 to-[#061426]/20"/>
    <div className="relative mx-auto grid max-w-[1500px] gap-8 px-6 pb-20 pt-10 lg:grid-cols-[1.02fr_.98fr] lg:px-10">
     <div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-blue-300/30 bg-blue-500/10 px-4 py-2 text-xs font-bold text-blue-200"><Sparkles size={14}/> IA ESPECIALIZADA EM NBR 5410</div>
      <h1 className="mt-6 text-5xl font-black leading-[.98] tracking-tight sm:text-6xl xl:text-7xl">Dimensione instalações elétricas com <span className="text-blue-400">Inteligência Artificial</span></h1>
      <p className="mt-6 max-w-2xl text-lg leading-7 text-slate-200">Crie projetos elétricos completos, com diagramas, listas de materiais e relatórios profissionais, de acordo com a <b className="text-white">NBR 5410</b>. Mais segurança, rapidez e precisão para engenheiros, eletricistas e projetistas.</p>
      <div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-7 py-3.5 font-bold">Começar agora <ArrowRight size={18}/></Link><a href="#como-funciona" className="inline-flex items-center gap-2 rounded-lg border border-white/50 px-6 py-3.5 font-semibold"><PlayCircle size={19}/> Ver demonstração</a></div>
      <div className="mt-9 grid grid-cols-2 gap-4 sm:grid-cols-5">{features.map(({icon:Icon,title})=><div key={title}><div className="mb-2 flex h-10 w-10 items-center justify-center rounded-full bg-blue-600"><Icon size={18}/></div><div className="text-xs font-semibold text-slate-200">{title}</div></div>)}</div>
     </div>
     <div className="relative hidden min-h-[520px] lg:block"><div className="absolute right-0 top-10 w-[90%] overflow-hidden rounded-[28px] border border-white/20 bg-slate-950/40 p-3 shadow-2xl"><img src="/assets/plant-visual.svg" alt="Planta elétrica 2D" className="w-full rounded-2xl"/></div><div className="absolute right-0 top-0 rounded-2xl bg-white p-4 text-slate-900 shadow-2xl"><b className="block text-sm">Projeto Residencial</b><b className="text-lg">2 Quartos</b><div className="text-xs text-slate-500">127/220V · Conforme NBR 5410</div></div><div className="absolute bottom-4 left-0 rounded-2xl bg-white p-4 text-slate-900 shadow-2xl"><div className="flex items-center gap-2 font-bold"><Bot className="text-blue-600"/> Com Inteligência Artificial</div><div className="mt-2 space-y-1 text-xs"><div>✓ Sugestões inteligentes</div><div>✓ Validação da norma</div><div>✓ Projetos mais rápidos</div></div></div></div>
    </div>
   </section>
   <section id="recursos" className="border-b bg-white"><div className="mx-auto grid max-w-[1500px] grid-cols-2 divide-x px-6 py-8 lg:grid-cols-4 lg:px-10">{[{i:Home,t:"Residencial",d:"Casas, apartamentos e condomínios."},{i:Building2,t:"Comercial",d:"Lojas, escritórios e pequenos comércios."},{i:Factory,t:"Industrial",d:"Galpões, indústrias e instalações especiais."},{i:FileText,t:"Memoriais e Relatórios",d:"Exportação profissional em PDF."}].map(({i:Icon,t,d})=><div key={t} className="px-5 text-center"><Icon className="mx-auto text-blue-600" size={35}/><h3 className="mt-2 font-bold">{t}</h3><p className="mt-1 text-sm text-slate-500">{d}</p></div>)}</div></section>
   <section id="sobre" className="bg-[#061a33] py-16 text-white"><div className="mx-auto grid max-w-[1500px] items-center gap-8 px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><h2 className="text-4xl font-black">Sua IA especializada<br/>em instalações elétricas</h2><p className="mt-4 max-w-xl text-slate-300">Obtenha dimensionamento, recomendações e validações de acordo com a NBR 5410 em poucos segundos.</p><Link to="/professor" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 font-bold">Conheça a IA <ArrowRight size={18}/></Link></div><div className="overflow-hidden rounded-3xl border border-blue-300/20"><img src="/assets/ai-visual.svg" alt="Professor ElectroCAD IA" className="w-full"/></div></div></section>
   <section id="como-funciona" className="bg-slate-50 py-16"><div className="mx-auto max-w-[1200px] px-6 text-center"><h2 className="text-4xl font-black">Como funciona?</h2><p className="mt-2 text-slate-500">Do seu projeto ao relatório completo em 4 passos simples.</p><div className="mt-10 grid gap-5 md:grid-cols-4">{[["1","Informe os Dados","Tipo de projeto, ambientes e carga instalada."],["2","A IA Processa","Dimensiona conforme a NBR 5410."],["3","Revise e Ajuste","Faça alterações quando necessário."],["4","Exporte o Projeto","Obtenha diagramas, memoriais e lista de materiais."]].map(([n,t,d])=><div key={n} className="rounded-2xl border bg-white p-6 text-left shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-600 font-bold text-white">{n}</span><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm text-slate-500">{d}</p></div>)}</div></div></section>
   <section className="bg-[#071c36] py-12 text-white"><div className="mx-auto grid max-w-[1200px] grid-cols-2 gap-8 px-6 text-center md:grid-cols-4">{[["+500","Projetos criados"],["+300","Profissionais"],["99%","Conforme NBR 5410"],["4.9","Avaliação dos usuários"]].map(([n,t])=><div key={t}><b className="text-4xl text-blue-400">{n}</b><p className="mt-1 text-sm text-slate-300">{t}</p></div>)}</div></section>
   <section id="planos" className="bg-white py-16"><div className="mx-auto max-w-[1200px] px-6"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Planos</p><h2 className="mt-2 text-4xl font-black">Escolha o plano ideal</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map(p=><article key={p.id} className={`relative flex flex-col rounded-3xl border p-7 ${p.name.toLowerCase()==="pro"?"border-blue-500 bg-blue-50/30 shadow-xl":"border-slate-200 bg-white shadow-sm"}`}><h3 className="text-xl font-bold">{p.name}</h3><p className="mt-3 min-h-[72px] text-sm text-slate-500">{p.description}</p><div className="mt-5 text-4xl font-black">{p.price}<span className="text-sm font-normal text-slate-500">/mês</span></div><ul className="mt-6 flex-1 space-y-3 text-sm text-slate-600">{p.features.map(x=><li key={x}><CheckCircle2 className="mr-2 inline text-blue-600" size={16}/>{x}</li>)}</ul><Link to="/register" className="mt-7 rounded-xl bg-blue-600 px-4 py-3 text-center font-bold text-white">Começar com {p.name}</Link></article>)}</div></div></section>
   <section id="integracoes" className="bg-slate-50 py-12"><div className="mx-auto grid max-w-[1200px] grid-cols-2 gap-4 px-6 md:grid-cols-4">{[[Calculator,"Projetista"],[Bot,"Professor IA"],[FileText,"Relatórios PDF"],[Users,"Gestão de clientes"]].map(([Icon,title]:any)=><div key={title} className="rounded-2xl border bg-white p-5 text-center shadow-sm"><Icon className="mx-auto text-blue-600"/><b className="mt-2 block">{title}</b></div>)}</div></section>
  </main>
  <footer id="contato" className="border-t bg-white"><div className="mx-auto flex max-w-[1500px] flex-col gap-2 px-6 py-8 text-sm text-slate-500 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} ElectroCAD-AI</span><span>Projetos elétricos com mais organização, tecnologia e segurança.</span></div></footer>
 </div>
}